using System;
using System.Drawing;
using System.Drawing.Drawing2D;
using System.IO;
using System.Windows.Forms;

static class Palette {
    public static Color Ink=Color.FromArgb(66,42,53),Muted=Color.FromArgb(150,116,129),Accent=Color.FromArgb(185,66,95),Background=Color.FromArgb(253,245,247),Line=Color.FromArgb(240,219,225),Rail=Color.FromArgb(62,34,49);
    public static Color Tint=Color.FromArgb(254,248,250),Soft=Color.FromArgb(253,240,245);
    public static GraphicsPath Round(Rectangle r,int radius){var p=new GraphicsPath();int d=radius*2;p.AddArc(r.X,r.Y,d,d,180,90);p.AddArc(r.Right-d,r.Y,d,d,270,90);p.AddArc(r.Right-d,r.Bottom-d,d,d,0,90);p.AddArc(r.X,r.Bottom-d,d,d,90,90);p.CloseFigure();return p;}
}
class Card : Panel {
    public Card(){DoubleBuffered=true;BackColor=Palette.Background;Padding=new Padding(20);}
    protected override void OnPaint(PaintEventArgs e){base.OnPaint(e);e.Graphics.SmoothingMode=SmoothingMode.AntiAlias;using(var path=Palette.Round(new Rectangle(0,0,Width-1,Height-1),15)){using(var fill=new SolidBrush(Color.White))e.Graphics.FillPath(fill,path);using(var pen=new Pen(Palette.Line))e.Graphics.DrawPath(pen,path);}using(var brush=new SolidBrush(Color.FromArgb(45,Palette.Accent)))e.Graphics.FillEllipse(brush,Width-43,12,7,7);}
}
class SoftButton : Button {
    public bool Primary,Dark;bool hover;
    public SoftButton(){SetStyle(ControlStyles.UserPaint|ControlStyles.AllPaintingInWmPaint|ControlStyles.OptimizedDoubleBuffer,true);FlatStyle=FlatStyle.Flat;FlatAppearance.BorderSize=0;Cursor=Cursors.Hand;AutoSize=false;Height=38;Margin=new Padding(0,0,8,0);}
    protected override void OnMouseEnter(EventArgs e){hover=true;Invalidate();base.OnMouseEnter(e);}protected override void OnMouseLeave(EventArgs e){hover=false;Invalidate();base.OnMouseLeave(e);}
    protected override void OnPaint(PaintEventArgs e){e.Graphics.SmoothingMode=SmoothingMode.AntiAlias;e.Graphics.Clear(Parent==null?Palette.Background:Parent.BackColor);Color fill=Primary?(Enabled?Palette.Accent:MainForm.BlendColor(Palette.Accent,Color.White,.4f)):Dark?(hover?MainForm.BlendColor(Palette.Rail,Palette.Accent,.75f):Palette.Rail):(hover?MainForm.BlendColor(Palette.Accent,Color.White,.17f):Palette.Soft);Color text=Primary||Dark?Color.White:Enabled?Palette.Ink:Palette.Muted;using(var path=Palette.Round(new Rectangle(0,0,Width-1,Height-1),9)){using(var brush=new LinearGradientBrush(ClientRectangle,Primary?MainForm.BlendColor(fill,Color.White,.84f):fill,fill,70))e.Graphics.FillPath(brush,path);if(!Primary&&!Dark)using(var pen=new Pen(Palette.Line))e.Graphics.DrawPath(pen,path);}TextRenderer.DrawText(e.Graphics,Text,Font,ClientRectangle,text,TextFormatFlags.HorizontalCenter|TextFormatFlags.VerticalCenter);if(Focused){using(var pen=new Pen(Color.FromArgb(90,Palette.Accent))){pen.DashStyle=DashStyle.Dot;e.Graphics.DrawRectangle(pen,4,4,Width-9,Height-9);}}}
}
class BrandMark : Control {
    public BrandMark(){Size=new Size(48,48);SetStyle(ControlStyles.UserPaint|ControlStyles.AllPaintingInWmPaint|ControlStyles.OptimizedDoubleBuffer,true);}
    public static void Draw(Graphics g,Rectangle box){g.SmoothingMode=SmoothingMode.AntiAlias;using(var path=Palette.Round(box,Math.Max(4,box.Width/4))){using(var b=new LinearGradientBrush(box,Color.FromArgb(220,117,143),Color.FromArgb(166,46,79),45))g.FillPath(b,path);}float s=box.Width/64f;var state=g.Save();g.TranslateTransform(box.X,box.Y);g.ScaleTransform(s,s);using(var pen=new Pen(Color.White,4f)){pen.StartCap=LineCap.Round;pen.EndCap=LineCap.Round;g.DrawBezier(pen,12,17,24,21,40,21,52,17);g.DrawLine(pen,16,28,48,28);g.DrawLine(pen,23,22,21,49);g.DrawLine(pen,41,22,43,49);}using(var brush=new SolidBrush(Color.White))g.FillPolygon(brush,new PointF[]{new PointF(29,33),new PointF(29,43),new PointF(37,38)});g.Restore(state);}
    protected override void OnPaint(PaintEventArgs e){Draw(e.Graphics,new Rectangle(1,1,Width-2,Height-2));}
}
class ShrineRail : Panel {
    readonly Timer animation=new Timer();float phase;bool animate=true;public bool Animate{get{return animate;}set{animate=value;Invalidate();}}public int ThemeIndex;
    public ShrineRail(){DoubleBuffered=true;animation.Interval=60;animation.Tick+=delegate{if(Animate&&Visible){phase+=1.8f;Invalidate();}};animation.Start();}
    protected override void OnPaint(PaintEventArgs e){base.OnPaint(e);var g=e.Graphics;g.SmoothingMode=SmoothingMode.AntiAlias;int y=Math.Max(490,Height-265);using(var pen=new Pen(Color.FromArgb(55,Palette.Accent),ThemeIndex==0?5:2)){
        if(ThemeIndex==0){g.DrawBezier(pen,22,y,72,y+13,117,y+13,166,y);g.DrawLine(pen,31,y+25,157,y+25);g.DrawLine(pen,53,y+8,49,y+130);g.DrawLine(pen,135,y+8,139,y+130);}
        else if(ThemeIndex==2){g.DrawEllipse(pen,25,y,138,138);g.DrawEllipse(pen,36,y+11,116,116);PointF[] star=new PointF[5];for(int j=0;j<5;j++){double a=(-90+j*144)*Math.PI/180;star[j]=new PointF(94+(float)Math.Cos(a)*58,y+69+(float)Math.Sin(a)*58);}g.DrawPolygon(pen,star);}
        else if(ThemeIndex==3){g.DrawEllipse(pen,48,y,92,92);g.DrawArc(pen,73,y-2,92,92,90,180);}
    }
    for(int i=0;i<15;i++){float px=10+(i*53)%Math.Max(20,Width-25)+(float)Math.Sin((phase+i*41)/70)*12;float py=(phase+i*71)%Math.Max(1,Height);var state=g.Save();g.TranslateTransform(px,py);g.RotateTransform(i*31+phase*.35f);using(var pen=new Pen(Color.FromArgb(90,MainForm.BlendColor(Palette.Accent,Color.White,.45f)),1.2f))using(var b=new SolidBrush(Color.FromArgb(75,MainForm.BlendColor(Palette.Accent,Color.White,.45f)))){
        if(ThemeIndex==1){for(int j=0;j<3;j++){var s=g.Save();g.RotateTransform(j*60);g.DrawLine(pen,0,-6,0,6);g.DrawLine(pen,0,-3,-2,-5);g.DrawLine(pen,0,3,2,5);g.Restore(s);}}
        else if(ThemeIndex==2){g.DrawLine(pen,-4,0,4,0);g.DrawLine(pen,0,-4,0,4);g.FillEllipse(b,-1,-1,2,2);}
        else if(ThemeIndex==4){Color[] rainbow={Color.Gold,Color.Salmon,Color.LightSkyBlue,Color.Plum,Color.PaleGreen};using(var gem=new SolidBrush(Color.FromArgb(120,rainbow[i%5])))g.FillPolygon(gem,new Point[]{new Point(0,-7),new Point(4,0),new Point(0,7),new Point(-4,0)});}
        else{using(var p=new GraphicsPath()){p.AddBezier(0,-6,8,-5,8,3,0,7);p.AddBezier(0,7,-4,0,-6,-3,0,-6);g.FillPath(b,p);}}
    }g.Restore(state);}}
    protected override void Dispose(bool disposing){if(disposing)animation.Dispose();base.Dispose(disposing);}
}
class ReimuBanner : Panel {
    Image illustration;
    public ReimuBanner(){DoubleBuffered=true;using(var stream=typeof(MainForm).Assembly.GetManifestResourceStream("Reimu.banner")){if(stream!=null)using(var img=Image.FromStream(stream))illustration=new Bitmap(img);}}
    public void SetArtwork(Image image){var previous=illustration;illustration=image;if(previous!=null)previous.Dispose();Invalidate(true);}
    protected override void OnPaintBackground(PaintEventArgs e){e.Graphics.Clear(Palette.Background);e.Graphics.SmoothingMode=SmoothingMode.AntiAlias;using(var path=Palette.Round(new Rectangle(0,0,Width-1,Height-1),16)){var saved=e.Graphics.Save();e.Graphics.SetClip(path);if(illustration!=null){float scale=Math.Max((float)Width/illustration.Width,(float)Height/illustration.Height);float w=illustration.Width*scale,h=illustration.Height*scale;e.Graphics.InterpolationMode=InterpolationMode.HighQualityBicubic;e.Graphics.DrawImage(illustration,new RectangleF((Width-w)/2,(Height-h)/2,w,h));}using(var wash=new LinearGradientBrush(new Rectangle(0,0,Width,Height),Color.FromArgb(155,255,248,243),Color.FromArgb(0,255,248,243),0f))e.Graphics.FillRectangle(wash,0,0,Width*2/3,Height);e.Graphics.Restore(saved);using(var pen=new Pen(Palette.Line))e.Graphics.DrawPath(pen,path);}}
    protected override void Dispose(bool disposing){if(disposing&&illustration!=null)illustration.Dispose();base.Dispose(disposing);}
}
partial class MainForm {
    Label linkCount=new Label();
    Label CopyLabel(string text,int size,bool bold){return new Label{Text=text,AutoSize=true,ForeColor=Palette.Ink,Font=new Font("Microsoft YaHei UI",size,bold?FontStyle.Bold:FontStyle.Regular),BackColor=Color.Transparent};}
    Button ActionButton(string text,EventHandler action,bool primary){var b=(SoftButton)Btn(text,action);b.Primary=primary;return b;}
    Panel TextField(TextBox field){var box=new Panel{Dock=DockStyle.Fill,BackColor=Palette.Tint,Padding=new Padding(10,8,10,5),Height=38};box.Paint+=delegate(object s,PaintEventArgs e){e.Graphics.SmoothingMode=SmoothingMode.AntiAlias;using(var path=Palette.Round(new Rectangle(0,0,box.Width-1,box.Height-1),6))using(var pen=new Pen(field.Focused?Palette.Accent:Palette.Line,field.Focused?1.6f:1f))e.Graphics.DrawPath(pen,path);};field.Enter+=delegate{box.Invalidate();};field.Leave+=delegate{box.Invalidate();};field.BorderStyle=BorderStyle.None;field.BackColor=box.BackColor;field.ForeColor=Palette.Ink;field.Dock=DockStyle.Fill;box.Controls.Add(field);return box;}
    TableLayoutPanel Grid(int cols,int rows){return new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=cols,RowCount=rows,BackColor=Color.White,Margin=new Padding(0)};}
    void OpenFolder(){try{Directory.CreateDirectory(folder.Text);System.Diagnostics.Process.Start("explorer.exe",Quote(folder.Text));}catch(Exception ex){MessageBox.Show(ex.Message);}}
    void InitializeDesign(){
        Text="映拾 · 幻想乡主题";ClientSize=new Size(1180,960);MinimumSize=new Size(1100,900);StartPosition=FormStartPosition.CenterScreen;Font=new Font("Microsoft YaHei UI",10);ForeColor=Palette.Ink;BackColor=Palette.Background;AutoScaleMode=AutoScaleMode.Dpi;
        using(var stream=typeof(MainForm).Assembly.GetManifestResourceStream("Yingshi.ico")){if(stream!=null)Icon=new Icon(stream);}
        var shell=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=2,RowCount=1,Margin=new Padding(0)};shell.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,188));shell.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100));Controls.Add(shell);
        var rail=new ShrineRail{Dock=DockStyle.Fill,BackColor=Palette.Rail,Padding=new Padding(22)};shell.Controls.Add(rail,0,0);characterRail=rail;
        var mark=new BrandMark{Location=new Point(24,32)};rail.Controls.Add(mark);var brand=CopyLabel("映拾",22,true);brand.ForeColor=Color.White;brand.Location=new Point(24,94);rail.Controls.Add(brand);
        var tagline=CopyLabel("幻想乡 · 影像收藏室",9,false);tagline.ForeColor=Color.FromArgb(218,174,189);tagline.Location=new Point(24,137);rail.Controls.Add(tagline);
        var nav=new FlowLayoutPanel{Location=new Point(20,205),Size=new Size(150,295),FlowDirection=FlowDirection.TopDown,WrapContents=false,BackColor=Palette.Rail};rail.Controls.Add(nav);characterNavigation=nav;
        foreach(var button in new Button[]{ActionButton("↓  新建下载",delegate{urls.Focus();},true),Btn("✦  角色图鉴",delegate{ShowCharacters();}),Btn("☷  高级设置",delegate{if(!busy)ShowAdvanced();}),Btn("▣  下载文件夹",delegate{OpenFolder();}),Btn("?  使用帮助",delegate{MessageBox.Show("粘贴链接 → 选择下载内容 → 开始下载。\n\n顶部角色栏可切换五种角色主题，角色图鉴可查看插画。\n主题选择与动态开关会记住。\n下载核心为 BBDown 1.6.3。\n\n映拾 5.0 · 幻想乡花映集\n东方 Project 原作：上海爱丽丝幻乐团 / ZUN\n本主题为同人设计，非官方产品。","映拾 · 使用帮助");})}){button.Width=148;button.Height=43;button.Margin=new Padding(0,0,0,12);var soft=(SoftButton)button;if(!soft.Primary)soft.Dark=true;nav.Controls.Add(button);}
        var mascot=new PictureBox{Size=new Size(150,170),Location=new Point(20,511),SizeMode=PictureBoxSizeMode.Zoom,BackColor=Color.Transparent};using(var stream=typeof(MainForm).Assembly.GetManifestResourceStream("Marisa.sticker")){if(stream!=null)using(var img=Image.FromStream(stream))mascot.Image=new Bitmap(img);}rail.Controls.Add(mascot);FormClosed+=delegate{if(mascot.Image!=null)mascot.Image.Dispose();};
        var magic=CopyLabel("普通的魔法使 · 雾雨魔理沙",8,false);magic.ForeColor=Color.FromArgb(224,185,200);magic.Location=new Point(22,694);rail.Controls.Add(magic);
        var petals=new CheckBox{Text="主题动态",Checked=true,AutoSize=true,ForeColor=Color.FromArgb(221,179,195),BackColor=Color.Transparent,Location=new Point(24,735),Font=new Font(Font.FontFamily,9)};petals.CheckedChanged+=delegate{rail.Animate=petals.Checked;SaveCharacterSettings();};rail.Controls.Add(petals);
        var credits=new Label{Text="映拾 5.0 · 东方同人主题\nPowered by BBDown",ForeColor=Color.FromArgb(197,155,173),Font=new Font(Font.FontFamily,8),Dock=DockStyle.Bottom,Height=60,BackColor=Color.Transparent};rail.Controls.Add(credits);
        var main=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=1,RowCount=7,Padding=new Padding(24,20,24,16),BackColor=Palette.Background};shell.Controls.Add(main,1,0);
        main.RowStyles.Add(new RowStyle(SizeType.Absolute,202));main.RowStyles.Add(new RowStyle(SizeType.Absolute,52));main.RowStyles.Add(new RowStyle(SizeType.Absolute,126));main.RowStyles.Add(new RowStyle(SizeType.Absolute,236));main.RowStyles.Add(new RowStyle(SizeType.Absolute,54));main.RowStyles.Add(new RowStyle(SizeType.Percent,100));main.RowStyles.Add(new RowStyle(SizeType.Absolute,36));
        main.SizeChanged+=delegate{bool compact=main.Height<920;main.RowStyles[0].Height=compact?170:202;main.RowStyles[1].Height=compact?46:52;main.RowStyles[2].Height=compact?108:126;};
        var hero=new ReimuBanner{Dock=DockStyle.Fill,Margin=new Padding(0,0,0,16)};main.Controls.Add(hero);var tag=CopyLabel("TOUHOU PROJECT  /  FAN THEME",8,true);tag.ForeColor=Color.FromArgb(176,85,110);tag.Location=new Point(29,24);hero.Controls.Add(tag);var heading=CopyLabel("映拾 · 幻想乡",26,true);heading.Font=new Font("Microsoft YaHei UI",26,FontStyle.Bold);heading.Location=new Point(26,53);hero.Controls.Add(heading);var sub=CopyLabel("把喜欢的瞬间，收藏成一场幻想。",11,false);sub.ForeColor=Color.FromArgb(138,90,107);sub.Location=new Point(29,109);hero.Controls.Add(sub);var heroine=CopyLabel("博丽灵梦  /  樱色的收藏时光",9,false);heroine.ForeColor=Palette.Accent;heroine.Location=new Point(29,145);hero.Controls.Add(heroine);characterBanner=hero;characterTitle=heading;characterSubtitle=sub;characterTag=tag;characterName=heroine;
        var themes=Row();themes.BackColor=Palette.Background;themes.Controls.Add(new Label{Text="角色主题",Width=76,Height=35,ForeColor=Palette.Muted,Padding=new Padding(0,9,0,0)});
        for(int i=0;i<CharacterThemes.Length;i++){int choice=i;var button=(SoftButton)Btn(CharacterThemes[i].Name,delegate{ApplyCharacter(choice);});button.Width=110;button.Height=35;button.Font=new Font(Font.FontFamily,9);characterButtons[i]=button;themes.Controls.Add(button);}var gallery=Btn("全部插画",delegate{ShowCharacters();});gallery.Width=100;gallery.Height=35;themes.Controls.Add(gallery);main.Controls.Add(themes);
        var links=new Card{Dock=DockStyle.Fill,Margin=new Padding(0,0,0,12)};main.Controls.Add(links);var lg=Grid(1,2);lg.RowStyles.Add(new RowStyle(SizeType.Absolute,30));lg.RowStyles.Add(new RowStyle(SizeType.Percent,100));links.Controls.Add(lg);
        var linkHeader=new Panel{Dock=DockStyle.Fill,BackColor=Color.White};lg.Controls.Add(linkHeader);linkHeader.Controls.Add(CopyLabel("01   视频链接",11,true));linkCount.Text="支持批量 · 每行一条";linkCount.ForeColor=Palette.Muted;linkCount.AutoSize=true;linkCount.Dock=DockStyle.Right;linkHeader.Controls.Add(linkCount);
        urls.Multiline=true;urls.ScrollBars=ScrollBars.Vertical;urls.TextChanged+=delegate{int count=0;foreach(var line in urls.Lines)if(line.Trim().Length>0)count++;linkCount.Text=count==0?"支持批量 · 每行一条":count+" 条待处理链接";};lg.Controls.Add(TextField(urls));
        var settings=new Card{Dock=DockStyle.Fill,Margin=new Padding(0,0,0,12)};main.Controls.Add(settings);var sg=Grid(1,4);sg.RowStyles.Add(new RowStyle(SizeType.Absolute,31));sg.RowStyles.Add(new RowStyle(SizeType.Absolute,69));sg.RowStyles.Add(new RowStyle(SizeType.Absolute,51));sg.RowStyles.Add(new RowStyle(SizeType.Percent,100));settings.Controls.Add(sg);sg.Controls.Add(CopyLabel("02   下载偏好",11,true));
        var choices=Grid(4,2);for(int i=0;i<4;i++)choices.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,i==2?31:23));choices.RowStyles.Add(new RowStyle(SizeType.Absolute,24));choices.RowStyles.Add(new RowStyle(SizeType.Percent,100));sg.Controls.Add(choices);
        string[] labels={"画质优先级","下载内容","解析模式","分 P 范围"};for(int i=0;i<4;i++){var label=CopyLabel(labels[i],9,false);label.ForeColor=Palette.Muted;choices.Controls.Add(label,i,0);}
        quality.Items.AddRange(new object[]{"最高可用画质","1080P 优先","720P 优先","480P 优先"});mode.Items.AddRange(new object[]{"视频 + 音频","仅音频","仅视频","仅弹幕","仅字幕","仅封面"});api.Items.AddRange(new object[]{"网页 WEB","TV · 尝试无水印片源","手机 APP","国际版 INTL"});
        var combos=new ComboBox[]{quality,mode,api};for(int i=0;i<3;i++){combos[i].DropDownStyle=ComboBoxStyle.DropDownList;combos[i].FlatStyle=FlatStyle.Flat;combos[i].BackColor=Color.FromArgb(253,240,245);combos[i].ForeColor=Palette.Ink;combos[i].Dock=DockStyle.Top;combos[i].SelectedIndex=0;combos[i].Margin=new Padding(0,0,14,0);choices.Controls.Add(combos[i],i,1);}pages.Text="ALL";var pageBox=TextField(pages);pageBox.Margin=new Padding(0,0,0,5);choices.Controls.Add(pageBox,3,1);
        var destination=Grid(3,1);destination.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,76));destination.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100));destination.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,86));sg.Controls.Add(destination);var dirLabel=CopyLabel("保存位置",9,false);dirLabel.Margin=new Padding(0,10,0,0);destination.Controls.Add(dirLabel,0,0);folder.Text=Path.Combine(root,"下载");var folderBox=TextField(folder);folderBox.Margin=new Padding(0,2,10,8);destination.Controls.Add(folderBox,1,0);destination.Controls.Add(Btn("浏览…",delegate{using(var picker=new FolderBrowserDialog()){if(picker.ShowDialog()==DialogResult.OK)folder.Text=picker.SelectedPath;}}),2,0);
        var small=Row();small.BackColor=Color.White;danmaku.Text="同时保存弹幕";danmaku.AutoSize=true;small.Controls.Add(danmaku);small.Controls.Add(new Label{Text="TV 模式取决于片源；分 P 可填 ALL / 1,3 / 2-5。",AutoSize=true,ForeColor=Palette.Muted,Font=new Font(Font.FontFamily,9),Margin=new Padding(20,3,0,0)});sg.Controls.Add(small);
        var actions=Row();actions.BackColor=Palette.Background;download=ActionButton("开始下载  ↓",async delegate{await Run(false,false);},true);download.Width=148;info=Btn("解析信息",async delegate{await Run(true,false);});login=Btn("账号与登录",delegate{if(!busy)ShowAccount();});cancel=Btn("停止任务",delegate{Stop();});cancel.Enabled=false;actions.Controls.AddRange(new Control[]{download,info,login,Btn("更多设置",delegate{if(!busy)ShowAdvanced();}),cancel});main.Controls.Add(actions);
        var activity=new Card{Dock=DockStyle.Fill,Margin=new Padding(0)};main.Controls.Add(activity);var ag=Grid(1,3);ag.RowStyles.Add(new RowStyle(SizeType.Absolute,32));ag.RowStyles.Add(new RowStyle(SizeType.Percent,100));ag.RowStyles.Add(new RowStyle(SizeType.Absolute,43));activity.Controls.Add(ag);
        var activityHeader=new Panel{Dock=DockStyle.Fill,BackColor=Color.White};activityHeader.Controls.Add(CopyLabel("03   下载动态",11,true));var clear=Btn("清空日志",delegate{if(!busy)log.Clear();});clear.Width=90;clear.Height=27;clear.Dock=DockStyle.Right;activityHeader.Controls.Add(clear);ag.Controls.Add(activityHeader);
        var logBox=new Panel{Dock=DockStyle.Fill,BackColor=Color.FromArgb(255,249,251)};log.Dock=DockStyle.Fill;log.ReadOnly=true;log.BorderStyle=BorderStyle.None;log.BackColor=logBox.BackColor;log.ForeColor=Color.FromArgb(109,80,94);log.Font=new Font("Microsoft YaHei UI",9);logBox.Padding=new Padding(10);logBox.Controls.Add(log);var empty=new Label{Text="准备好了，贴上第一条链接吧。\n下载速度、解析结果和任务状态会显示在这里。",ForeColor=Palette.Muted,BackColor=logBox.BackColor,TextAlign=ContentAlignment.MiddleCenter,Dock=DockStyle.Fill};logBox.Controls.Add(empty);empty.BringToFront();empty.Click+=delegate{urls.Focus();};log.TextChanged+=delegate{empty.Visible=log.TextLength==0;};ag.Controls.Add(logBox);
        var entry=Grid(3,1);entry.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,90));entry.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100));entry.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,80));entry.Padding=new Padding(0,6,0,0);entry.Controls.Add(new Label{Text="画质序号",AutoSize=true,ForeColor=Palette.Muted,Margin=new Padding(0,7,0,0)},0,0);var responseBox=TextField(response);responseBox.Margin=new Padding(0,0,10,0);entry.Controls.Add(responseBox,1,0);var send=Btn("发送",delegate{SendInput();});send.Width=75;send.Height=32;entry.Controls.Add(send,2,0);ag.Controls.Add(entry);
        var footer=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=2,RowCount=1,BackColor=Palette.Background,Padding=new Padding(0,10,0,0)};footer.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100));footer.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,170));status.Text="就绪 · 等待新任务";status.AutoSize=false;status.Dock=DockStyle.Fill;status.ForeColor=Palette.Muted;footer.Controls.Add(status,0,0);progress.Dock=DockStyle.Fill;progress.Style=ProgressBarStyle.Marquee;progress.Visible=false;footer.Controls.Add(progress,1,0);main.Controls.Add(footer);
        RestoreCharacter();petals.Checked=characterRail.Animate;
        AcceptButton=download;response.KeyDown+=delegate(object sender,KeyEventArgs e){if(e.KeyCode==Keys.Enter){SendInput();e.SuppressKeyPress=true;}};
    }
    void ShowAccount(){
        using(var dialog=new Form{Text="映拾 · 账号与登录",ClientSize=new Size(560,350),Font=Font,BackColor=Palette.Background,StartPosition=FormStartPosition.CenterParent,FormBorderStyle=FormBorderStyle.FixedDialog,MaximizeBox=false,MinimizeBox=false}){
            var card=new Card{Dock=DockStyle.Fill,Margin=new Padding(16)};dialog.Padding=new Padding(20);dialog.Controls.Add(card);var grid=Grid(1,5);int[] heights={40,50,42,60,55};foreach(int h in heights)grid.RowStyles.Add(new RowStyle(SizeType.Absolute,h));card.Controls.Add(grid);grid.Controls.Add(CopyLabel("登录，获取账号可用的画质",15,true));grid.Controls.Add(new Label{Text="网页使用常规扫码登录，TV 模式使用 TV 扫码登录。\n需要手动填写时，也可以在下方输入 Cookie。",AutoSize=true,ForeColor=Palette.Muted});var input=new TextBox{Text=cookie.Text,UseSystemPasswordChar=true};grid.Controls.Add(TextField(input));var choices=Row();choices.BackColor=Color.White;choices.Controls.Add(ActionButton("网页扫码",async delegate{cookie.Text=input.Text;dialog.Close();await Run(false,true);},true));choices.Controls.Add(Btn("TV 扫码",async delegate{cookie.Text=input.Text;dialog.Close();commandOverride="logintv";try{await Run(false,true);}finally{commandOverride=null;}}));choices.Controls.Add(Btn("保存并返回",delegate{cookie.Text=input.Text;dialog.Close();}));grid.Controls.Add(choices);grid.Controls.Add(new Label{Text="Cookie 只保留在本次运行中。登录凭据由 BBDown 管理。",ForeColor=Palette.Muted,AutoSize=true,Font=new Font(Font.FontFamily,9)});dialog.ShowDialog(this);
        }
    }
}
